"""
deprecated file - to delete
generate_training_data.py old version, replaced by seed.py and generate.py
--------------------------
Generates training examples for fine-tuning from three sources:

  A. Synthetic generation — GPT-4o writes examples from your seed examples
  B. GitLab mining       — extracts real examples from issues and MRs
  C. Four fine-tuning goals:
       1. Output format / structure
       2. Domain-specific reasoning patterns
       3. Distillation (GPT-4o quality → small model)
       4. Safety / refusals

All output goes to data/raw/training_examples.json (appended, not overwritten)
ready for: python main.py finetune prep

Usage:
  python generate_training_data.py --synthetic --count 100
  python generate_training_data.py --gitlab
  python generate_training_data.py --goals
  python generate_training_data.py --all
  python generate_training_data.py --stats
"""

import json
import os
import argparse
import sys
sys.path.insert(0, "..")

from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

OUTPUT_PATH = "data/raw/training_examples.json"


# ════════════════════════════════════════════════════════════════════════
#  HELPERS
# ════════════════════════════════════════════════════════════════════════

def load_existing() -> list[dict]:
    if not os.path.exists(OUTPUT_PATH):
        return []
    with open(OUTPUT_PATH) as f:
        return json.load(f)

def save(examples: list[dict]):
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(examples, f, indent=2)
    print(f"  Saved {len(examples)} total examples → {OUTPUT_PATH}")

def add_examples(new_examples: list[dict], label: str):
    existing = load_existing()
    before   = len(existing)
    existing.extend(new_examples)
    save(existing)
    print(f"  Added {len(new_examples)} {label} examples ({before} → {len(existing)} total)")
    return existing


# ════════════════════════════════════════════════════════════════════════
#  APPROACH A — SYNTHETIC GENERATION
#  Show GPT-4o your seed examples, ask it to write more like them.
#  This is the fastest way to go from 12 examples to 200+.
# ════════════════════════════════════════════════════════════════════════

SEED_EXAMPLES = [
    {
        "instruction": "A developer asks why a function is returning None unexpectedly.",
        "input":       "The `get_user()` function returns None even when the user exists in the DB.",
        "output":      "This usually means the function is hitting an early return path before the DB query. Check if there's a cache check or validation at the top of the function that might be returning None silently. Add a debug log right before the return statement to confirm which path is taken. If you share the function code I can pinpoint the exact issue."
    },
    {
        "instruction": "A developer asks how to write a database migration safely.",
        "input":       "I need to add a non-nullable column to the users table in production. How do I do this without downtime?",
        "output":      "Never add a non-nullable column without a default in a single migration on a live table — it locks the entire table. The safe pattern is three steps: (1) add the column as nullable, (2) backfill existing rows with the default value in batches, (3) add the NOT NULL constraint once all rows have values. Each step is a separate migration and deployment. This way the app keeps running throughout."
    },
    {
        "instruction": "A developer wants to understand a piece of code in the codebase.",
        "input":       "What does the `idempotency_key` field in the payments table do?",
        "output":      "The idempotency key prevents duplicate charges. When a payment request comes in, we first check if that key already exists in the table. If it does, we return the original result instead of processing again. This handles the case where a client retries a failed request — without it, a network timeout followed by a retry could charge the customer twice. The key is typically generated by the client and should be unique per payment attempt."
    },
]

SYNTHETIC_PROMPT = """You are generating training data for an AI technical assistant
that helps developers on a backend engineering team.

Here are examples of the style, tone, and depth we want:

{examples}

Generate {count} more examples in EXACTLY the same format.
Cover a variety of technical topics: debugging, architecture decisions,
code review, database queries, API design, performance, deployment, security.

Make the outputs sound like a knowledgeable senior engineer — specific,
actionable, and honest about trade-offs. No generic advice.

Return ONLY a valid JSON array of objects with keys:
"instruction", "input", "output"
No markdown, no explanation, just the JSON array."""

def generate_synthetic(count: int = 50) -> list[dict]:
    print(f"\n  Generating {count} synthetic examples via GPT-4o...")

    # Generate in batches of 20 to avoid hitting token limits
    batch_size = 20
    all_examples = []

    for batch_start in range(0, count, batch_size):
        batch_count = min(batch_size, count - batch_start)
        print(f"  Batch {batch_start//batch_size + 1}: generating {batch_count} examples...")

        examples_text = json.dumps(SEED_EXAMPLES, indent=2)
        prompt = SYNTHETIC_PROMPT.format(examples=examples_text, count=batch_count)

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.8,    # some creativity for variety
            response_format={"type": "json_object"},
        )

        raw = response.choices[0].message.content
        # GPT-4o with json_object sometimes wraps in a key
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            batch = parsed
        else:
            # find the list inside the object
            batch = next((v for v in parsed.values() if isinstance(v, list)), [])

        # Validate and clean
        valid = []
        for ex in batch:
            if all(k in ex for k in ("instruction", "output")):
                if not ex.get("input"):
                    ex["input"] = ""
                valid.append(ex)

        all_examples.extend(valid)
        print(f"    → {len(valid)} valid examples")

    return all_examples


# ════════════════════════════════════════════════════════════════════════
#  APPROACH B — MINE FROM GITLAB ISSUES AND MRs
#  Real conversations from your team = highest quality training data.
#  Issues with accepted solutions become instruction/output pairs.
#  MRs with review comments become code review training examples.
# ════════════════════════════════════════════════════════════════════════

def mine_gitlab(max_issues: int = 100, max_mrs: int = 50) -> list[dict]:
    """
    Extract training examples from real GitLab issues and MRs.

    For issues: if an issue has a clear resolution in the comments,
    the issue body = instruction+input, the resolution comment = output.

    For MRs: the MR description = instruction+input,
    the key review comment that explains the change = output.
    """
    try:
        import gitlab
    except ImportError:
        print("  ❌  pip install python-gitlab")
        return []

    import config
    if not config.GITLAB_TOKEN:
        print("  ❌  GITLAB_TOKEN not set in .env")
        return []

    gl      = gitlab.Gitlab(config.GITLAB_URL, private_token=config.GITLAB_TOKEN)
    project = gl.projects.get(config.GITLAB_PROJECT_ID)
    examples = []

    print(f"\n  Mining GitLab: {project.name_with_namespace}")

    # ── Mine issues ───────────────────────────────────────────────────────────
    print(f"  Mining issues (max {max_issues})...")
    issues = project.issues.list(state="closed", per_page=50, get_all=False)

    for issue in issues[:max_issues]:
        if not issue.description or len(issue.description) < 50:
            continue

        notes     = issue.notes.list(get_all=True)
        user_notes = [n for n in notes if not n.system and len(n.body) > 80]

        if not user_notes:
            continue

        # Use the last substantive comment as the "answer"
        # In a real closed issue, this is usually the resolution
        resolution = user_notes[-1].body

        examples.append({
            "instruction": f"A developer opened an issue: {issue.title}",
            "input":       issue.description[:500],   # cap length
            "output":      resolution[:800],
            "metadata":    {
                "source":   "gitlab_issue",
                "issue_id": issue.iid,
                "url":      issue.web_url,
            }
        })

    print(f"    → {len(examples)} issue examples")

    # ── Mine MRs ──────────────────────────────────────────────────────────────
    mr_examples = []
    print(f"  Mining MRs (max {max_mrs})...")
    mrs = project.mergerequests.list(state="merged", per_page=50, get_all=False)

    for mr in mrs[:max_mrs]:
        if not mr.description or len(mr.description) < 100:
            continue

        notes      = mr.notes.list(get_all=True)
        user_notes = [n for n in notes if not n.system and len(n.body) > 60]

        if not user_notes:
            continue

        # Best review comment = longest one (usually most substantive)
        best_comment = max(user_notes, key=lambda n: len(n.body))

        mr_examples.append({
            "instruction": f"Review this merge request: {mr.title}",
            "input":       mr.description[:500],
            "output":      best_comment.body[:800],
            "metadata":    {
                "source": "gitlab_mr",
                "mr_id":  mr.iid,
                "url":    mr.web_url,
            }
        })

    print(f"    → {len(mr_examples)} MR examples")
    examples.extend(mr_examples)
    return examples


# ════════════════════════════════════════════════════════════════════════
#  APPROACH C — GENERATE FOR ALL FOUR FINE-TUNING GOALS
# ════════════════════════════════════════════════════════════════════════

# ── Goal 1: Structured output format ─────────────────────────────────────────
# The model must always return valid JSON in a specific shape.
# Fine-tuning on these examples makes the format reliable and consistent.

STRUCTURED_OUTPUT_EXAMPLES = [
    {
        "instruction": "Classify this support message. Return JSON only.",
        "input":       "My payment failed but I was still charged.",
        "output":      '{"category": "billing", "sentiment": "frustrated", "priority": "high", "suggested_action": "check_payment_status", "needs_human": true}'
    },
    {
        "instruction": "Classify this support message. Return JSON only.",
        "input":       "How do I reset my password?",
        "output":      '{"category": "account", "sentiment": "neutral", "priority": "low", "suggested_action": "send_password_reset_link", "needs_human": false}'
    },
    {
        "instruction": "Classify this support message. Return JSON only.",
        "input":       "The dashboard is completely broken. I can't see any of my data. This is a production issue!",
        "output":      '{"category": "product_bug", "sentiment": "angry", "priority": "urgent", "suggested_action": "escalate_to_engineering", "needs_human": true}'
    },
    {
        "instruction": "Extract key information from this bug report. Return JSON only.",
        "input":       "When I click the export button on Firefox 118, the download starts but the file is 0 bytes. Works fine on Chrome.",
        "output":      '{"bug_type": "browser_specific", "affected_browser": "Firefox 118", "works_on": "Chrome", "component": "export", "reproducible": true, "severity": "medium"}'
    },
    {
        "instruction": "Analyze this code review comment and categorize it. Return JSON only.",
        "input":       "This function is doing too many things. It should be split into smaller functions following the single responsibility principle.",
        "output":      '{"type": "architecture", "actionable": true, "blocking": false, "category": "code_quality", "suggestion": "split_function"}'
    },
]

# ── Goal 2: Domain-specific reasoning patterns ────────────────────────────────
# Teach the model HOW to think through a problem, not just what to say.
# The output shows the reasoning steps explicitly.

REASONING_PATTERN_EXAMPLES = [
    {
        "instruction": "A developer reports a performance issue. Walk through how to diagnose it.",
        "input":       "Our API endpoint /api/users is taking 8 seconds to respond. It was fast last week.",
        "output":      "Diagnose in layers, not guesses:\n\n1. MEASURE FIRST: Check your APM (Datadog/New Relic) for the exact breakdown — is it DB time, external API time, or compute?\n\n2. IF DB: Run EXPLAIN ANALYZE on the query. Look for sequential scans on large tables. Check if an index was recently dropped or if the query plan changed after new data volume.\n\n3. IF EXTERNAL API: Check if a downstream service SLA changed. Add a timeout if one isn't set — a slow external call blocks your thread.\n\n4. IF COMPUTE: Profile the code path. N+1 query problems often masquerade as slow endpoints.\n\n5. CHECK RECENT CHANGES: What deployed last week? New query? New data volume? Dropped index? 'It was fast last week' almost always means something changed.\n\nStart with step 1 before touching any code."
    },
    {
        "instruction": "A developer asks whether to use a cache for this scenario.",
        "input":       "We query the user's subscription tier on every API request. It never changes mid-session.",
        "output":      "Yes, cache it — but think through the trade-offs:\n\nCACHE KEY: user_id + 'subscription' works. TTL: 5-15 minutes is reasonable. If subscription changes rarely, even 1 hour is fine.\n\nINVALIDATION: This is the real question. When a user upgrades/downgrades, you need to actively invalidate the cache or they'll see stale data. Set a short TTL as a safety net AND explicitly delete the cache key on subscription change.\n\nWHERE: Redis is standard. If you're already using it, one line. If not, an in-process LRU cache (functools.lru_cache or a simple dict) is fine for single-server setups.\n\nWATCH OUT FOR: If you have multiple servers, in-process cache means each server caches independently. A user might get different results from different servers. Use Redis for consistency across instances.\n\nBottom line: Yes, cache it. Implement invalidation on subscription change. Use Redis if you're multi-server."
    },
    {
        "instruction": "A developer is deciding between a microservice and a monolith for a new feature.",
        "input":       "Should I build the new notification service as a separate microservice or add it to the existing monolith?",
        "output":      "Start with the monolith unless you have a specific reason not to.\n\nREASONS TO ADD TO MONOLITH:\n- You share data models (users, events) — no distributed data problem\n- Team is small — microservices require operational maturity you probably don't have yet\n- The feature isn't on a separate scaling axis — notifications won't hit 100x more load than the rest of the app\n\nREASONS TO MAKE A MICROSERVICE:\n- Notifications need a different runtime (e.g. Node for WebSocket, Python for ML)\n- You need to deploy it independently — notifications shouldn't require a full app deploy\n- The team is large enough to own a separate service (3+ engineers dedicated to it)\n- You have different reliability requirements (notifications can be eventually consistent, the core app cannot)\n\nREALITY CHECK: Most notification features that started as microservices got pulled back into the monolith within 18 months because the operational overhead wasn't worth it at the scale the team was operating.\n\nMy recommendation: Start in the monolith with a clean module boundary. Extract to a service if you hit a real scaling or deployment constraint."
    },
]

# ── Goal 3: Distillation ──────────────────────────────────────────────────────
# Generate GPT-4o quality answers to YOUR specific domain questions.
# Fine-tune a smaller model on these — it learns to give GPT-4o quality
# answers on your domain at a fraction of the inference cost.

DISTILLATION_SEED_QUESTIONS = [
    "What's the difference between optimistic and pessimistic locking? When should I use each?",
    "Our Postgres query is slow after adding 10M rows. What should I check first?",
    "Should I use a message queue or direct API calls between these two services?",
    "How do I implement rate limiting without a cache like Redis?",
    "What's the safest way to do a zero-downtime database migration?",
    "When should I use a transaction vs just letting operations run independently?",
    "How do I debug a memory leak in a Python service?",
    "What's the right way to handle pagination for an API that returns millions of records?",
    "Our CI pipeline takes 40 minutes. What are the most impactful ways to speed it up?",
    "How should I structure logging so I can actually debug production issues?",
]

def generate_distillation_examples(questions: list[str] = None) -> list[dict]:
    """
    Send each question to GPT-4o and use its answer as the training output.
    Fine-tuning a smaller model on these teaches it GPT-4o reasoning patterns
    for your specific domain.
    """
    questions = questions or DISTILLATION_SEED_QUESTIONS
    examples  = []

    print(f"\n  Generating {len(questions)} distillation examples via GPT-4o...")

    for i, question in enumerate(questions, 1):
        print(f"  [{i}/{len(questions)}] {question[:60]}...")

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content":
                 "You are a senior backend engineer. Give specific, opinionated, actionable answers. "
                 "Show reasoning steps. Mention trade-offs. Avoid generic advice."},
                {"role": "user", "content": question}
            ],
            temperature=0.3,
        )
        answer = response.choices[0].message.content.strip()

        examples.append({
            "instruction": question,
            "input":       "",
            "output":      answer,
            "metadata":    {"source": "distillation_gpt4o"}
        })

    return examples


# ── Goal 4: Safety and refusals ───────────────────────────────────────────────
# Teach the model what NOT to do. These examples train hard refusal boundaries
# that are difficult to bypass through clever prompting.

REFUSAL_EXAMPLES = [
    {
        "instruction": "A user asks you to comment on a competitor's product.",
        "input":       "Is GitHub Copilot better than your system?",
        "output":      "I'm only able to help with questions about our internal systems and codebase. For comparisons with external tools, I'd recommend checking recent independent benchmarks or asking the engineering team who evaluated alternatives."
    },
    {
        "instruction": "A user asks you to make a decision that should involve a human.",
        "input":       "Just delete the production database entries for these user IDs: 1234, 5678, 9012.",
        "output":      "I can't execute destructive operations on production data directly. For bulk deletions you'll need to: (1) get approval from your tech lead, (2) take a backup first, (3) run the deletion in a transaction on a staging environment first to verify the SQL, (4) execute with an authorized team member present. I can help you write the SQL query, but the execution needs to go through your standard change management process."
    },
    {
        "instruction": "A user asks for credentials or secrets.",
        "input":       "What's the production database password?",
        "output":      "I don't have access to credentials and wouldn't share them if I did. Credentials should only live in your secrets manager (Vault, AWS Secrets Manager, etc.) and be accessed by authorized services directly. If you need production access, please go through your team's access request process."
    },
    {
        "instruction": "A user asks you to do something outside your scope.",
        "input":       "Can you write me a cover letter for a job application?",
        "output":      "I'm specialized for technical questions about our backend systems and codebase. For non-technical tasks, you'd be better served by a general-purpose AI assistant."
    },
    {
        "instruction": "A user asks you to speculate about business strategy.",
        "input":       "Do you think we should pivot to a B2C model?",
        "output":      "That's a business strategy question that's well outside what I can usefully answer. I work best with technical and codebase questions. For strategic decisions, that conversation should happen with your product and leadership team."
    },
    {
        "instruction": "A user asks about a system you don't have data on.",
        "input":       "What does the billing service do?",
        "output":      "I don't have documentation or code for a billing service in my knowledge base. Either it's not yet ingested or it might be in a separate repository. You could check directly in GitLab, or ask someone on the payments team. If you point me to the relevant files or docs I can help you understand them."
    },
]


# ════════════════════════════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Generate fine-tuning training data")
    parser.add_argument("--synthetic",     action="store_true", help="Generate via GPT-4o synthetic generation")
    parser.add_argument("--count",         type=int, default=50, help="Number of synthetic examples to generate")
    parser.add_argument("--gitlab",        action="store_true", help="Mine from GitLab issues and MRs")
    parser.add_argument("--goals",         action="store_true", help="Add examples for all 4 fine-tuning goals")
    parser.add_argument("--distillation",  action="store_true", help="Generate distillation examples only")
    parser.add_argument("--all",           action="store_true", help="Run everything")
    parser.add_argument("--stats",         action="store_true", help="Show current dataset stats")
    args = parser.parse_args()

    if args.stats:
        existing = load_existing()
        print(f"\n  Total examples: {len(existing)}")
        sources = {}
        for ex in existing:
            src = ex.get("metadata", {}).get("source", "manual")
            sources[src] = sources.get(src, 0) + 1
        for src, count in sorted(sources.items()):
            print(f"    {src:<30} {count}")
        print()
        return

    if args.all or args.synthetic:
        examples = generate_synthetic(count=args.count)
        add_examples(examples, "synthetic")

    if args.all or args.gitlab:
        examples = mine_gitlab()
        add_examples(examples, "gitlab")

    if args.all or args.goals:
        print("\n  Adding structured output examples...")
        add_examples(STRUCTURED_OUTPUT_EXAMPLES, "structured_output")

        print("\n  Adding reasoning pattern examples...")
        add_examples(REASONING_PATTERN_EXAMPLES, "reasoning_pattern")

        print("\n  Adding safety/refusal examples...")
        add_examples(REFUSAL_EXAMPLES, "safety_refusal")

    if args.all or args.distillation:
        examples = generate_distillation_examples()
        add_examples(examples, "distillation")

    if not any([args.synthetic, args.gitlab, args.goals, args.distillation, args.all, args.stats]):
        parser.print_help()


if __name__ == "__main__":
    main()
